### ISSUE TITLE
pip install from source fails due to requirements.txt not being included in .tar.gz dist

### ISSUE THREAD

**Issue by dciborow** [fairlearn/fairlearn#683]
#### Describe the bug
When installing from src dist, fairlearn fails due to missing requirements.txt file.

#### Steps/Code to Reproduce
```shell
pip download --no-binary :all: -d ./ fairlearn==0.5.0
```

#### Expected Results
```shell
Collecting fairlearn==0.4.6
  Downloading fairlearn-0.4.6.tar.gz (10.5 MB)
     |████████████████████████████████| 10.5 MB 16.6 MB/s
```
#### Actual Results
```shell
Collecting fairlearn==0.5.0
  Using cached fairlearn-0.5.0.tar.gz (12.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-download-muxh63mo/fairlearn_d4026bee74b547c9957a0a48e60fe570/setup.py'"'"'; __file__='"'"'/tmp/pip-download-muxh63mo/fairlearn_d4026bee74b547c9957a0a48e60fe570/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-bfv_4scs
         cwd: /tmp/pip-download-muxh63mo/fairlearn_d4026bee74b547c9957a0a48e60fe570/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-download-muxh63mo/fairlearn_d4026bee74b547c9957a0a48e60fe570/setup.py", line 12, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

#### Screenshots
![image](https://user-images.githubusercontent.com/9027725/105106478-ee4a6280-5a83-11eb-8dce-d1ac9ff76c39.png)

#### Versions
OS: Ubuntu (Windows Subsystem for Linux)
Python: 3..7.17
pip: 20.3.3
fairlearn: 0.5.0

**Comment by riedgar-ms** [comment]
I'm assuming you didn't mean Python 2.7.17 above....

This is not a use case we've considered. Can you tell us what you're trying to do?

**Comment by dciborow** [comment]
@riedgar-ms , i meant python 3.7!

**Comment by TamaraAtanasoska** [comment]
@riedgar-ms can this one be closed?

**Comment by riedgar-ms** [comment]
@TamaraAtanasoska I think so.
